// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBH4UnrXoN4JQI8VoRmWc9UwciFg3Ln0sU',
    appId: '1:57827590030:web:3d7c3890ef6527be49eedf',
    messagingSenderId: '57827590030',
    projectId: 'fireb-590d8',
    authDomain: 'fireb-590d8.firebaseapp.com',
    storageBucket: 'fireb-590d8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGY52GNMj3T80wodihBwcSkjTmQCmVgKo',
    appId: '1:57827590030:android:74996215c297e4e449eedf',
    messagingSenderId: '57827590030',
    projectId: 'fireb-590d8',
    storageBucket: 'fireb-590d8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA63875g0LFjyO5M2fEbTj3K-xxQQzQ_4Y',
    appId: '1:57827590030:ios:4ab7f60c36e1ec9749eedf',
    messagingSenderId: '57827590030',
    projectId: 'fireb-590d8',
    storageBucket: 'fireb-590d8.firebasestorage.app',
    iosBundleId: 'com.example.hw5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA63875g0LFjyO5M2fEbTj3K-xxQQzQ_4Y',
    appId: '1:57827590030:ios:4ab7f60c36e1ec9749eedf',
    messagingSenderId: '57827590030',
    projectId: 'fireb-590d8',
    storageBucket: 'fireb-590d8.firebasestorage.app',
    iosBundleId: 'com.example.hw5',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBH4UnrXoN4JQI8VoRmWc9UwciFg3Ln0sU',
    appId: '1:57827590030:web:ea50554da1055a6b49eedf',
    messagingSenderId: '57827590030',
    projectId: 'fireb-590d8',
    authDomain: 'fireb-590d8.firebaseapp.com',
    storageBucket: 'fireb-590d8.firebasestorage.app',
  );
}
